/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphicaliouserinterface;

import java.awt.Color;

/**
 *
 * @author Owner
 */
public class graphicalIO extends javax.swing.JFrame implements userinterface.UserInterface{

    usercommandhandler.UserCommandHandler myUserCommandHandler;
    /**
     * Creates new form graphicalIO
     */
    public graphicalIO() {
        initComponents();
    }
    
    @Override
    public void update(String theMessage) {
        server_messages.setText(theMessage);
        if (theMessage.contains("PB3"))
        {
            String msg = theMessage.split("/")[0];
            pb_3_text_field.setText(msg.substring(3));
        }
        if (theMessage.contains("PB1"))
        {
            String msg = theMessage.split("/")[0];
            pb_1_text_field.setText(msg.substring(3));
        }
        if (theMessage.contains("PB2"))
        {
            String msg = theMessage.split("/")[0];
            pb_2_text_field.setText(msg.substring(3));
        }
    }
    
    
    public void setCommandHandler(usercommandhandler.UserCommandHandler myUserCommandHandler) {
        this.myUserCommandHandler = myUserCommandHandler;
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        connect_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        server_messages = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        disconnect_button = new javax.swing.JButton();
        get_time_button = new javax.swing.JButton();
        quit_button = new javax.swing.JButton();
        led_1 = new javax.swing.JToggleButton();
        led_2 = new javax.swing.JToggleButton();
        led_3 = new javax.swing.JToggleButton();
        led_4 = new javax.swing.JToggleButton();
        gpb_1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pb_1_text_field = new javax.swing.JTextField();
        pb_2_text_field = new javax.swing.JTextField();
        pb_3_text_field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        connect_button.setText("Connect");
        connect_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connect_buttonActionPerformed(evt);
            }
        });

        server_messages.setColumns(20);
        server_messages.setRows(5);
        jScrollPane1.setViewportView(server_messages);

        jLabel1.setText("Server Messages");

        disconnect_button.setText("Disconnect");
        disconnect_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconnect_buttonActionPerformed(evt);
            }
        });

        get_time_button.setText("Get Temp");
        get_time_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_time_buttonActionPerformed(evt);
            }
        });

        quit_button.setText("Quit");
        quit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quit_buttonActionPerformed(evt);
            }
        });

        led_1.setText("LED 1 OFF");
        led_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                led_1ActionPerformed(evt);
            }
        });

        led_2.setText("LED 2 OFF");
        led_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                led_2ActionPerformed(evt);
            }
        });

        led_3.setText("LED 3 OFF");
        led_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                led_3ActionPerformed(evt);
            }
        });

        led_4.setText("LED 4 OFF");
        led_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                led_4ActionPerformed(evt);
            }
        });

        gpb_1.setText("GET PB 1");
        gpb_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gpb_1MouseClicked(evt);
            }
        });

        jLabel3.setText("GET PB 2");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setText("GET PB 3");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(led_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(led_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(led_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(led_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(gpb_1)
                                .addGap(18, 18, 18)
                                .addComponent(pb_1_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(pb_2_text_field))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(pb_3_text_field)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(connect_button, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(disconnect_button, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(get_time_button, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(98, 98, 98))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(disconnect_button, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(get_time_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(connect_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(led_1)
                            .addComponent(gpb_1)
                            .addComponent(pb_1_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(led_2)
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(pb_2_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addComponent(led_3)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(led_4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(pb_3_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(quit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connect_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connect_buttonActionPerformed
        // TODO add your handling code here:
        myUserCommandHandler.execute("c");
    }//GEN-LAST:event_connect_buttonActionPerformed

    private void disconnect_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconnect_buttonActionPerformed
        // TODO add your handling code here:
        myUserCommandHandler.execute("d");
    }//GEN-LAST:event_disconnect_buttonActionPerformed

    private void get_time_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_time_buttonActionPerformed
        // TODO add your handling code here:
        myUserCommandHandler.execute("t");
    }//GEN-LAST:event_get_time_buttonActionPerformed

    private void quit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quit_buttonActionPerformed
        // TODO add your handling code here:
        myUserCommandHandler.execute("q");
    }//GEN-LAST:event_quit_buttonActionPerformed

    private void led_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_led_1ActionPerformed
        // TODO add your handling code here:
        if (!led_1.isSelected())
        {
            led_1.setText("LED 1 OFF");
            myUserCommandHandler.execute("L1off");
        }
        else
        {
            led_1.setText("LED 1 ON");
            led_1.setBackground(Color.green);
            myUserCommandHandler.execute("L1on");
        }
    }//GEN-LAST:event_led_1ActionPerformed

    private void led_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_led_2ActionPerformed
        // TODO add your handling code here:
        if (!led_2.isSelected())
        {
            led_2.setText("LED 2 OFF");
            myUserCommandHandler.execute("L2off");
        }
        else
        {
            led_2.setText("LED 2 ON");
            led_2.setBackground(Color.green);
            myUserCommandHandler.execute("L2on");
        }
    }//GEN-LAST:event_led_2ActionPerformed

    private void led_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_led_3ActionPerformed
        // TODO add your handling code here:
        if (!led_3.isSelected())
        {
            led_3.setText("LED 3 OFF");
            myUserCommandHandler.execute("L3off");
        }
        else
        {
            led_3.setText("LED 3 ON");
            led_3.setBackground(Color.green);
            myUserCommandHandler.execute("L3on");
        }
    }//GEN-LAST:event_led_3ActionPerformed

    private void led_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_led_4ActionPerformed
        // TODO add your handling code here:
        if (!led_4.isSelected())
        {
            led_4.setText("LED 4 OFF");
            myUserCommandHandler.execute("L4off");
        }
        else
        {
            led_4.setText("LED 4 ON");
            led_4.setBackground(Color.green);
            myUserCommandHandler.execute("L4on");
        }
    }//GEN-LAST:event_led_4ActionPerformed

    private void gpb_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gpb_1MouseClicked
        // TODO add your handling code here:
        myUserCommandHandler.execute("gpb1");
    }//GEN-LAST:event_gpb_1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        myUserCommandHandler.execute("gpb2");
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        myUserCommandHandler.execute("gpb3");
    }//GEN-LAST:event_jLabel4MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton connect_button;
    private javax.swing.JButton disconnect_button;
    private javax.swing.JButton get_time_button;
    private javax.swing.JLabel gpb_1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton led_1;
    private javax.swing.JToggleButton led_2;
    private javax.swing.JToggleButton led_3;
    private javax.swing.JToggleButton led_4;
    private javax.swing.JTextField pb_1_text_field;
    private javax.swing.JTextField pb_2_text_field;
    private javax.swing.JTextField pb_3_text_field;
    private javax.swing.JButton quit_button;
    private javax.swing.JTextArea server_messages;
    // End of variables declaration//GEN-END:variables
}
